### ISSUE TITLE
Chrome Launcher - Help users launch Chrome/Canary/Chromium automagically

### ISSUE THREAD

**Issue by digitaldesigndj** [dosyago/22120#1]
https://github.com/GoogleChrome/chrome-launcher

Just an idea. : )

I've used this project before to automate launching Chrome & friends. This could help lower some barriers to entry for this project, for users not so comfortable launching browsers from a CLI. It would give us a place to bake in the dev port number selection.

**Comment by digitaldesigndj** [comment]
Also, totally random. You could use port `22120`? For kicks? 🆒 😎

**Comment by crislin2046** [comment]
Thanks for these two suggestions. I'm doing it now. 

:) 😎

**Comment by crislin2046** [comment]
Closed in https://github.com/dosyago/22120/releases/tag/v1.1.7
