### ISSUE TITLE
[Feature] Selectively track like bookmarks

### ISSUE THREAD

**Issue by alber70g** [dosyago/22120#17]
Is there a way to selectively track where I browse. I'd like to have a way that is similar to saving bookmarks. E.g. hit a button to save the current page to make it re-searchable again.

**Comment by crislin2046** [comment]
you mean instead of saving everything you browse, only the pages you manually select?

if so, what's the main advantage your feel over having that instead of saving everything?

**Comment by alber70g** [comment]
I read a lot of stuff online, but only _some_ things are worth saving. Currently I do that by bookmarking them, but that's not sufficient as I cannot search through the contents of each link, so I'd like to have them stored as pages. Just not everything I browse is worthwhile to save.

**Comment by crislin2046** [comment]
Okay I got it. sounds worthwhile. thank you

would you be okay to install a helper extension that works with 22120, to get this functionally? in that case it could probably happen automatically when you bookmark a page

alternately, would you find it okay if a small overlay button was added to every page? clicking that button could trigger this page be saved

**Comment by alber70g** [comment]
I think a helper extension would be cool. Whenever clicking cmd+D (in my case) it would store it.

Furthermore, it might be nice if it can also "crawl and store" current bookmarks somehow?

**Comment by crislin2046** [comment]
Okay, cool. Thanks for the feedback. I'll open an issue for this.

Not sure about the crawl and store current, for now. Could be a lot of work but I understand what you mean.

**Comment by crisdosaygo** [comment]
@alber70g Closed! Implemented! Re #98 https://github.com/i5ik/DiskerNet/commit/39dcfadb0975bb96987ff8c6dbc383db4853d086
