### ISSUE TITLE
Helper extension to save a page ONLY when a bookmark is created

### ISSUE THREAD

**Issue by crislin2046** [dosyago/22120#18]
Chrome extensions can hook the `onCreated` event of the `bookmarks` API. 

We could then communicate with the controller via some endpoint on localhost:22120 and instruct it to save resources whose fetches originated from this target (the active tab), and reload that tab to begin saving.

The button could continue to remain in 'record' mode for that tab as long as you that tab is on the same domain, or until it is switched off.

If you change tabs, the record mode indicator may change, because each tab will have its own record mode state.

I don't think it's so simple as saying "only record the page load" because you can have dynamic content (single page app routes that don't create a navigation request, but change the view, and things like 'page preview' tooltips and hovercards that create views on the page from dynamic content that a person may want to explore from the saved copy, not to mention the 'when i scroll down lazily load images' behavior many pages now have).

It's not as simple as recording a single page load. In effect this feature is about defining the 'extent' of a single page, which, considering dynamic content and all the (possibly cross-origin) resources it can pull, a sort of vague and ambiguous concept.

That being said, I think the current idea captures it in the best possible way so far: a record button that starts when you add a bookmark, and keeps going for that tab as long as the domain is the same and until you switch it off. 

Actually probably better to make it "record until a top level navigation" is triggered. Then there's a closer alignment between the idea of bookmark and what's saved. A bookmark doesn't stretch to all other pages on the same domain. You need to rebookmark each one. 

This lets me think of another idea, we have a blacklist, perhaps we also need a whitelist. 

Save everything from domains that you whitelist. You can add a domain to the whitelist at any time via the control panel @ http://localhost:22120

This was originally inspired by #17 

@alber70g please jump in and give feedback if you think this is straying from what you want or if anything sounds weird to you here.

**Comment by crisdosaygo** [comment]
Closed! Implemented! Re #98 https://github.com/i5ik/DiskerNet/commit/39dcfadb0975bb96987ff8c6dbc383db4853d086
