### ISSUE TITLE
Handle SPA URL changes

### ISSUE THREAD

**Issue by crislin2046** [dosyago/22120#20]
When history push is used, you don't get a new top level fetch request for the URL, but the URL can change.

This means, the URL you have in your address bar may not be the one we have saved, even tho we have saved all the resources required to actually click through to that URL from the original URL.

Example:

- start at CNN
- Click a few articles, and a SPA updates the URL without reloading the top frame
- Switch mode to serve and reload the top frame (the page), 
- See "we have not saved this data"

What's a good solution to this that doesn't impact people's browsing experience but gets them the saves they would expect from what their URL looks like?

The problem is really URLs are no longer about "location" but people still think they are. In reality, they *sometimes* are about location, but people think they always mean location. But since SPA and history push URL is more a symbolic representation of location and view rather than an actual representation of location. 

How to do this?

Not sure right now.

**Comment by cris691** [comment]
Fixed in release. All URLS will go to index. May not cache tho. Who knows?
