### ISSUE TITLE
Creating fresh cache doesn't seem to be working to avoid cache hits

### ISSUE THREAD

**Issue by crislin2046** [dosyago/22120#21]
Cache hits mean we don't save it as no network request occurs. 

We could always tap into the cache API domain in devtools, but I think it's simpler just to tell the browser not to use cache.

This manifests as, for example, No favicons on any page in serve mode (because favicon are mostly pulled via 304 or browser cache)

How to solve this?

No idea right now.

**Comment by cris691** [comment]
This is fixed in upcoming release. It was simply a type missing function call from temp cache directory argument.
