### ISSUE TITLE
32bit version

### ISSUE THREAD

**Issue by dataarchivist** [dosyago/22120#24]
Hey, is it may possible to make an 32bit version too? Some archivist computers still run under this (like my own). :)

**Comment by crislin2046** [comment]
sure just need to build for the platform

in the meantime clone the repo and try these commands in its directory, you'll need LTS node JS and npm installed 

```console
npm i -g nexe npx
npx webpack && nexe -t windows-x32 -i 22120.js -r "./?.22120.js" -r "./public/*" && nexe -t linux-x32 -o 22120.nix -i 22120.js -r "./?.22120.js" -r "./public/*" && nexe -t macos-x32 -o 22120.mac -i 22120.js -r "./?.22120.js" -r "./public/*"
```

that will try to build 32 bit executables for each platform

**Comment by cris691** [comment]
Fixed in latest release.
