### ISSUE TITLE
Adding a domain blacklist

### ISSUE THREAD

**Issue by termermc** [dosyago/22120#3]
﻿Hi, just took a look at your project, and would love to try it out, but I've noticed there's no mention of a configurable domain blacklist anywhere. It'd be pretty important for someone who uses this tool for most of their browsing, since many people I'd imagine wouldn't like to save content from certain... NSFW domains. It would be excellent if you could add something like that.
Good luck with the project!

**Comment by crislin2046** [comment]
The project works well with ad blockers. 

I see you need something different. 

I think we can implement this.

**Comment by termermc** [comment]
Thanks

**Comment by crislin2046** [comment]
I'm thinking like `blacklist.json` you can put it in the archive directory.

In other words, archive dir is:

`$HOME/22120-arc/public/library`

But we could make

`$HOME/22120-arc/blacklist.json`

And you can make that yourself, say:

```blacklist.json:
[
  "domain1.com",
  "domain2.com"
]

**Comment by crislin2046** [comment]
Can compile a regex from a list of strings

and check that before archiving

**Comment by crislin2046** [comment]
@termermc implemented! 😄

**Comment by termermc** [comment]
Awesome! Thank you!
