### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by umaar** [dosyago/22120#33]
How much effort would it be to get a site like youtube to work with this? I noticed the `What about streaming content?` section in your readme, but wondering what it'd take and what the limitations are?

Current the page loads, but video does not play.

**Comment by cris691** [comment]
I don't understand it too well. Seems it would take a lot of special case code, which is why I avoided.

World it be impossible for you to take a closer look?

**Comment by umaar** [comment]
It's something I was thinking about, maybe in the future I can look! Thanks for considering it anyway.

**Comment by cris691** [comment]
Oh I didn't consider it. just told you what I think about it already. I'm grateful for your issue! Thanks, @umaar
