### ISSUE TITLE
Are you aware of webrecorder/conifer?

### ISSUE THREAD

**Issue by nicopace** [dosyago/22120#34]
I think your projects overlap, and would be great to see you working together :)
https://conifer.rhizome.org/

**Comment by cris691** [comment]
I don't want to put my stuff together with someone else if I can make money off this myself. I don't want to work together with a competitor. Why would I give up my autonomy and merge my project that I created myself with someone else's? Where's the benefit for me?

I want full direction over the things that I do unless someone's prepared to pay me a lot of money to take it off my hands. So I'm going to keep working on this myself if I do work on it.

But maybe you just meant work together on some sort of standard for archiving to be honest I don't really like the existing standards and I think I can probably do a better one myself and I don't want to change the way I'm doing it to fit someone else's standard if I don't think they're that much of a good idea which I don't. 

You got it? 

But thank you for the issue I found that this project had sort of been incorporated into a nonprofit...that's useful. And thanks for your star I appreciate it
