### ISSUE TITLE
Multiple-request handling suggestion: store content with timestamps as part of the filename

### ISSUE THREAD

**Issue by Joshfindit** [dosyago/22120#4]
The internet archive famously does this and it works quite well.
It does have the tradeoff of increasing the overall size when duplicates are stored, but it’s a more accurate way of recording pages as requesting the same page even an hour apart can result in a totally different page.

**Comment by crislin2046** [comment]
I don't know how I'd do that and mesh it with serving the pages.

Like how are we supposed to know which version to serve?

I think maybe we could store an archive prefixed by a date.

And then you have multiple archives, and you can pick which day you want.

So we change the archive format to be

`$HOME/22120-arc/public/library/<date>/<origin>/<sha 1 key hash>.json`

**Comment by crislin2046** [comment]
At the same time, I think git already solves this problem. As someone mentioned in the comments on HN and as I had the idea before. Using git to version an archive would be cool. 

Then the 'dates' are internal (to the .git system), and you could just check out an archive with resources up to a particular date. That's probably the simplest way to do it as well.

**Comment by crislin2046** [comment]
I think the best way to do this is using git. 

Could always build an integration between UI and git in future, but for now, closing and marking 'possible future improvement'
